import React from 'react';
// Assuming these hooks/contexts are correctly defined in '../../App' and '../../hooks/useScreenSize'
import { useTheme, useLanguage } from '../../App';
import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import { useScreenSize } from '../../hooks/useScreenSize';

// Translation object (kept as provided)
const translations = {
    en: {
      title: "Privacy Policy",
      subtitle: "OUR COMMITMENT TO YOUR PRIVACY",
      lastUpdated: "Last updated: April 19, 2025",
      intro: [
        "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
        "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator."
      ],
      sections: {
        interpretation: {
          title: "Interpretation and Definitions",
          interpretation: {
            title: "Interpretation",
            content: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
          },
          definitions: {
            title: "Definitions",
            content: "For the purposes of this Privacy Policy:",
            items: [
              "<strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.",
              "<strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
              "<strong>Company</strong> (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to legion agency.",
              "<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
              "<strong>Country</strong> refers to: Egypt",
              "<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
              "<strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.",
              "<strong>Service</strong> refers to the Website.",
              "<strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
              "<strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.",
              "<strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
              "<strong>Website</strong> refers to legion agency, accessible from <a href=\"https://www.legionagency.tech/\" style=\"color: var(--primary-color); text-decoration: none;\" rel=\"external nofollow noopener\" target=\"_blank\">https://www.legionagency.tech/</a>",
              "<strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
            ]
          }
        },
        dataCollection: {
          title: "Collecting and Using Your Personal Data",
          types: {
            title: "Types of Data Collected",
            personalData: {
              title: "Personal Data",
              content: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
              items: [
                "Email address",
                "Address, State, Province, ZIP/Postal code, City",
                "Usage Data"
              ]
            },
            usageData: {
              title: "Usage Data",
              content: [
                "Usage Data is collected automatically when using the Service.",
                "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
                "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
                "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device."
              ]
            },
            socialMedia: {
              title: "Information from Third-Party Social Media Services",
              content: [
                "The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:",
                "If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.",
                "You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy."
              ],
              items: [
                "Google",
                "Facebook",
                "Instagram",
                "Twitter",
                "LinkedIn"
              ]
            },
            tracking: {
              title: "Tracking Technologies and Cookies",
              content: [
                "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:",
                "Cookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on <a href=\"https://www.termsfeed.com/blog/cookies/#What_Are_Cookies\" style=\"color: var(--primary-color); text-decoration: none;\" target=\"_blank\">TermsFeed website</a> article."
              ],
              items: [
                "<strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
                "<strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)."
              ],
              cookieTypes: [
                {
                  title: "Necessary / Essential Cookies",
                  details: [
                    "Type: Session Cookies",
                    "Administered by: Us",
                    "Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
                  ]
                },
                {
                  title: "Cookies Policy / Notice Acceptance Cookies",
                  details: [
                    "Type: Persistent Cookies",
                    "Administered by: Us",
                    "Purpose: These Cookies identify if users have accepted the use of cookies on the Website."
                  ]
                },
                {
                  title: "Functionality Cookies",
                  details: [
                    "Type: Persistent Cookies",
                    "Administered by: Us",
                    "Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
                  ]
                }
              ]
            }
          }
        },
        use: {
          title: "Use of Your Personal Data",
          content: "The Company may use Personal Data for the following purposes:",
          items: [
            "<strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.",
            "<strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
            "<strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
            "<strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
            "<strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
            "<strong>To manage Your requests:</strong> To attend and manage Your requests to Us.",
            "<strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
            "<strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."
          ],
          sharing: {
            content: "We may share Your personal information in the following situations:",
            items: [
              "<strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.",
              "<strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
              "<strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
              "<strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.",
              "<strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.",
              "<strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent."
            ]
          }
        },
        retention: {
          title: "Retention of Your Personal Data",
          content: [
            "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
            "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."
          ]
        },
        transfer: {
          title: "Transfer of Your Personal Data",
          content: [
            "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
            "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
            "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information."
          ]
        },
        deletion: {
          title: "Delete Your Personal Data",
          content: [
            "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
            "Our Service may give You the ability to delete certain information about You from within the Service.",
            "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
            "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so."
          ]
        },
        disclosure: {
          title: "Disclosure of Your Personal Data",
          business: {
            title: "Business Transactions",
            content: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy."
          },
          law: {
            title: "Law Enforcement",
            content: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)."
          },
          legal: {
            title: "Other Legal Requirements",
            content: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
            items: [
              "Comply with a legal obligation",
              "Protect and defend the rights or property of the Company",
              "Prevent or investigate possible wrongdoing in connection with the Service",
              "Protect the personal safety of Users of the Service or the public",
              "Protect against legal liability"
            ]
          }
        },
        security: {
          title: "Security of Your Personal Data",
          content: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
        },
        children: {
          title: "Children's Privacy",
          content: [
            "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
            "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."
          ]
        },
        links: {
          title: "Links to Other Websites",
          content: [
            "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
            "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."
          ]
        },
        changes: {
          title: "Changes to this Privacy Policy",
          content: [
            "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
            "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy.",
            "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
          ]
        },
        contact: {
          title: "Contact Us",
          content: "If you have any questions about this Privacy Policy, You can contact us:",
          items: [
            "By email: info@legionagency.tech"
          ]
        }
      },
      footer: "Generated using <a href=\"https://www.termsfeed.com/privacy-policy-generator/\" style=\"color: var(--primary-color); text-decoration: none;\" target=\"_blank\">TermsFeed Privacy Policy Generator</a>"
    },
    ar: {
      title: "سياسة الخصوصية",
      subtitle: "التزامنا بخصوصيتك",
      lastUpdated: "آخر تحديث: 19 أبريل 2025",
      intro: [
        "تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا بشأن جمع واستخدام والكشف عن معلوماتك عند استخدامك للخدمة، وتخبرك بحقوق الخصوصية الخاصة بك وكيف يحميك القانون.",
        "نستخدم بياناتك الشخصية لتوفير الخدمة وتحسينها. باستخدام الخدمة، فإنك توافق على جمع واستخدام المعلومات وفقًا لسياسة الخصوصية هذه. تم إنشاء سياسة الخصوصية هذه بمساعدة مولد سياسة الخصوصية."
      ],
      sections: {
        interpretation: {
          title: "التفسير والتعريفات",
          interpretation: {
            title: "التفسير",
            content: "الكلمات التي تبدأ بحرف كبير لها معانٍ محددة ضمن الشروط التالية. التعريفات التالية لها نفس المعنى بغض النظر عما إذا كانت تظهر بصيغة المفرد أو الجمع."
          },
          definitions: {
            title: "التعريفات",
            content: "لغرض سياسة الخصوصية هذه:",
            items: [
              "<strong>الحساب</strong> يعني حسابًا فريدًا تم إنشاؤه لك للوصول إلى خدمتنا أو أجزاء من خدمتنا.",
              "<strong>الشريك</strong> يعني كيانًا يسيطر أو يتم التحكم فيه أو يكون تحت سيطرة مشتركة مع طرف، حيث تعني \"السيطرة\" ملكية 50% أو أكثر من الأسهم أو الحصة في الأسهم أو غيرها من الأوراق المالية التي لها الحق في التصويت لانتخاب المديرين أو غيرها من السلطات الإدارية.",
              "<strong>الشركة</strong> (يشار إليها إما بـ \"الشركة\"، \"نحن\"، \"لنا\" أو \"خاصتنا\" في هذه الاتفاقية) تشير إلى وكالة ليجيون.",
              "<strong>ملفات تعريف الارتباط</strong> هي ملفات صغيرة يتم وضعها على جهاز الكمبيوتر الخاص بك، أو الجهاز المحمول، أو أي جهاز آخر بواسطة موقع ويب، تحتوي على تفاصيل تاريخ تصفحك على ذلك الموقع من بين استخداماته العديدة.",
              "<strong>الدولة</strong> تشير إلى: مصر",
              "<strong>الجهاز</strong> يعني أي جهاز يمكنه الوصول إلى الخدمة مثل جهاز كمبيوتر، هاتف محمول، أو جهاز لوحي رقمي.",
              "<strong>البيانات الشخصية</strong> هي أي معلومات تتعلق بفرد محدد أو يمكن تحديده.",
              "<strong>الخدمة</strong> تشير إلى الموقع الإلكتروني.",
              "<strong>مزود الخدمة</strong> يعني أي شخص طبيعي أو اعتباري يعالج البيانات نيابة عن الشركة. يشير إلى الشركات أو الأفراد من الطرف الثالث الموظفين من قبل الشركة لتسهيل الخدمة، أو تقديم الخدمة نيابة عن الشركة، أو أداء الخدمات المتعلقة بالخدمة، أو مساعدة الشركة في تحليل كيفية استخدام الخدمة.",
              "<strong>خدمة وسائل التواصل الاجتماعي من طرف ثالث</strong> تشير إلى أي موقع ويب أو موقع شبكة اجتماعية يمكن للمستخدم من خلاله تسجيل الدخول أو إنشاء حساب لاستخدام الخدمة.",
              "<strong>بيانات الاستخدام</strong> تشير إلى البيانات التي يتم جمعها تلقائيًا، إما التي يتم إنشاؤها من خلال استخدام الخدمة أو من البنية التحتية للخدمة نفسها (على سبيل المثال، مدة زيارة الصفحة).",
              "<strong>الموقع الإلكتروني</strong> يشير إلى وكالة ليجيون، يمكن الوصول إليه من <a href=\"https://www.legionagency.tech/\" style=\"color: var(--primary-color); text-decoration: none;\" rel=\"external nofollow noopener\" target=\"_blank\">https://www.legionagency.tech/</a>",
              "<strong>أنت</strong> تعني الفرد الذي يصل أو يستخدم الخدمة، أو الشركة، أو أي كيان قانوني آخر يقوم هذا الفرد بالوصول إلى الخدمة أو استخدامها نيابة عنه، حسب الاقتضاء."
            ]
          }
        },
        dataCollection: {
          title: "جمع واستخدام بياناتك الشخصية",
          types: {
            title: "أنواع البيانات التي يتم جمعها",
            personalData: {
              title: "البيانات الشخصية",
              content: "أثناء استخدام خدمتنا، قد نطلب منك تزويدنا بمعلومات تعريف شخصية معينة يمكن استخدامها للاتصال بك أو التعرف عليك. قد تشمل المعلومات التعريفية الشخصية، على سبيل المثال لا الحصر:",
              items: [
                "عنوان البريد الإلكتروني",
                "العنوان، الولاية، المحافظة، الرمز البريدي، المدينة",
                "بيانات الاستخدام"
              ]
            },
            usageData: {
              title: "بيانات الاستخدام",
              content: [
                "يتم جمع بيانات الاستخدام تلقائيًا عند استخدام الخدمة.",
                "قد تشمل بيانات الاستخدام معلومات مثل عنوان بروتوكول الإنترنت لجهازك (مثل عنوان IP)، نوع المتصفح، إصدار المتصفح، صفحات خدمتنا التي تزورها، وقت وتاريخ زيارتك، الوقت الذي تقضيه على تلك الصفحات، معرفات الجهاز الفريدة وبيانات تشخيصية أخرى.",
                "عندما تصل إلى الخدمة بواسطة جهاز محمول أو من خلاله، قد نجمع معلومات معينة تلقائيًا، بما في ذلك، على سبيل المثال لا الحصر، نوع الجهاز المحمول الذي تستخدمه، المعرف الفريد لجهازك المحمول، عنوان IP لجهازك المحمول، نظام تشغيل جهازك المحمول، نوع متصفح الإنترنت المحمول الذي تستخدمه، معرفات الجهاز الفريدة وبيانات تشخيصية أخرى.",
                "قد نجمع أيضًا المعلومات التي يرسلها متصفحك كلما زرت خدمتنا أو عندما تصل إلى الخدمة بواسطة جهاز محمول أو من خلاله."
              ]
            },
            socialMedia: {
              title: "المعلومات من خدمات وسائل التواصل الاجتماعي من طرف ثالث",
              content: [
                "تتيح الشركة لك إنشاء حساب وتسجيل الدخول لاستخدام الخدمة من خلال خدمات وسائل التواصل الاجتماعي من طرف ثالث التالية:",
                "إذا قررت التسجيل من خلال أو منحنا الوصول إلى خدمة وسائل التواصل الاجتماعي من طرف ثالث، فقد نجمع بيانات شخصية مرتبطة بالفعل بحساب خدمة وسائل التواصل الاجتماعي من طرف ثالث الخاص بك، مثل اسمك، عنوان بريدك الإلكتروني، أنشطتك أو قائمة جهات الاتصال المرتبطة بذلك الحساب.",
                "قد يكون لديك أيضًا خيار مشاركة معلومات إضافية مع الشركة من خلال حساب خدمة وسائل التواصل الاجتماعي من طرف ثالث الخاص بك. إذا اخترت تقديم هذه المعلومات والبيانات الشخصية، أثناء التسجيل أو غير ذلك، فإنك تمنح الشركة الإذن باستخدام ومشاركة وتخزين هذه المعلومات بطريقة تتفق مع سياسة الخصوصية هذه."
              ],
              items: [
                "جوجل",
                "فيسبوك",
                "إنستغرام",
                "تويتر",
                "لينكدإن"
              ]
            },
            tracking: {
              title: "تقنيات التتبع وملفات تعريف الارتباط",
              content: [
                "نستخدم ملفات تعريف الارتباط وتقنيات التتبع المشابهة لتتبع النشاط على خدمتنا وتخزين معلومات معينة. تقنيات التتبع المستخدمة هي الإشارات، العلامات، والنصوص البرمجية لجمع وتتبع المعلومات ولتحسين وتحليل خدمتنا. التقنيات التي نستخدمها قد تشمل:",
                "يمكن أن تكون ملفات تعريف الارتباط \"دائمة\" أو \"مؤقتة\". تبقى ملفات تعريف الارتباط الدائمة على جهاز الكمبيوتر الشخصي الخاص بك أو جهازك المحمول عندما تكون غير متصل بالإنترنت، بينما يتم حذف ملفات تعريف الارتباط المؤقتة بمجرد إغلاق متصفح الويب الخاص بك. يمكنك معرفة المزيد عن ملفات تعريف الارتباط على <a href=\"https://www.termsfeed.com/blog/cookies/#What_Are_Cookies\" style=\"color: var(--primary-color); text-decoration: none;\" target=\"_blank\">موقع TermsFeed</a>."
              ],
              items: [
                "<strong>ملفات تعريف الارتباط أو ملفات تعريف ارتباط المتصفح.</strong> ملف تعريف الارتباط هو ملف صغير يوضع على جهازك. يمكنك توجيه متصفحك لرفض جميع ملفات تعريف الارتباط أو للإشارة عندما يتم إرسال ملف تعريف ارتباط. ومع ذلك، إذا لم تقبل ملفات تعريف الارتباط، فقد لا تتمكن من استخدام بعض أجزاء خدمتنا. ما لم تكن قد قمت بضبط إعدادات متصفحك بحيث يرفض ملفات تعريف الارتباط، فقد تستخدم خدمتنا ملفات تعريف الارتباط.",
                "<strong>إشارات الويب.</strong> قد تحتوي أقسام معينة من خدمتنا ورسائلنا الإلكترونية على ملفات إلكترونية صغيرة تُعرف باسم إشارات الويب (يشار إليها أيضًا باسم صور GIF الشفافة، علامات البكسل، وصور GIF أحادية البكسل) التي تتيح للشركة، على سبيل المثال، عد المستخدمين الذين زاروا تلك الصفحات أو فتحوا بريدًا إلكترونيًا ولأغراض إحصائية أخرى متعلقة بالموقع (على سبيل المثال، تسجيل شعبية قسم معين والتحقق من سلامة النظام والخادم)."
              ],
              cookieTypes: [
                {
                  title: "ملفات تعريف الارتباط الضرورية / الأساسية",
                  details: [
                    "النوع: ملفات تعريف الارتباط المؤقتة",
                    "إدارتها: نحن",
                    "الغرض: هذه الملفات ضرورية لتزويدك بالخدمات المتاحة من خلال الموقع الإلكتروني ولتمكينك من استخدام بعض ميزاته. فهي تساعد في مصادقة المستخدمين ومنع الاستخدام الاحتيالي لحسابات المستخدم. بدون هذه الملفات، لا يمكن تقديم الخدمات التي طلبتها، ونستخدم هذه الملفات فقط لتزويدك بتلك الخدمات."
                  ]
                },
                {
                  title: "ملفات تعريف الارتباط لسياسة/إشعار قبول ملفات تعريف الارتباط",
                  details: [
                    "النوع: ملفات تعريف الارتباط الدائمة",
                    "إدارتها: نحن",
                    "الغرض: تحدد هذه الملفات ما إذا كان المستخدمون قد قبلوا استخدام ملفات تعريف الارتباط على الموقع الإلكتروني."
                  ]
                },
                {
                  title: "ملفات تعريف الارتباط الوظيفية",
                  details: [
                    "النوع: ملفات تعريف الارتباط الدائمة",
                    "إدارتها: نحن",
                    "الغرض: تتيح لنا هذه الملفات تذكر الخيارات التي تقوم بها عند استخدام الموقع الإلكتروني، مثل تذكر تفاصيل تسجيل الدخول أو تفضيلات اللغة. الغرض من هذه الملفات هو تزويدك بتجربة أكثر تخصيصًا وتجنب إعادة إدخال تفضيلاتك في كل مرة تستخدم فيها الموقع."
                  ]
                }
              ]
            }
          }
        },
        use: {
          title: "استخدام بياناتك الشخصية",
          content: "يجوز للشركة استخدام البيانات الشخصية للأغراض التالية:",
          items: [
            "<strong>لتوفير وصيانة خدمتنا</strong>، بما في ذلك مراقبة استخدام خدمتنا.",
            "<strong>لإدارة حسابك:</strong> لإدارة تسجيلك كمستخدم للخدمة. يمكن أن تمنحك البيانات الشخصية التي تقدمها الوصول إلى وظائف مختلفة للخدمة المتاحة لك كمستخدم مسجل.",
            "<strong>لتنفيذ العقد:</strong> تطوير وتلبية وتنفيذ عقد الشراء للمنتجات أو العناصر أو الخدمات التي اشتريتها أو أي عقد آخر معنا من خلال الخدمة.",
            "<strong>للاتصال بك:</strong> للاتصال بك عبر البريد الإلكتروني، المكالمات الهاتفية، الرسائل النصية القصيرة، أو غيرها من أشكال الاتصال الإلكترونية المعادلة، مثل إشعارات تطبيق الهاتف المحمول بشأن التحديثات أو الاتصالات الإعلامية المتعلقة بالوظائف أو المنتجات أو الخدمات المتعاقد عليها، بما في ذلك تحديثات الأمان، عندما يكون ذلك ضروريًا أو معقولًا لتنفيذها.",
            "<strong>لتزويدك</strong> بالأخبار، العروض الخاصة والمعلومات العامة حول السلع والخدمات والأحداث الأخرى التي نقدمها والتي تشبه تلك التي اشتريتها أو استفسرت عنها ما لم تكن قد اخترت عدم تلقي مثل هذه المعلومات.",
            "<strong>لإدارة طلباتك:</strong> لحضور وإدارة طلباتك إلينا.",
            "<strong>لنقل الأعمال:</strong> يجوز لنا استخدام معلوماتك لتقييم أو إجراء دمج، تصفية، إعادة هيكلة، إعادة تنظيم، حل، أو بيع أو نقل بعض أو كل أصولنا، سواء كمشروع مستمر أو كجزء من الإفلاس، التصفية، أو إجراء مماثل، حيث تكون البيانات الشخصية التي نحتفظ بها عن مستخدمي خدمتنا من بين الأصول المنقولة.",
            "<strong>لأغراض أخرى</strong>: يجوز لنا استخدام معلوماتك لأغراض أخرى، مثل تحليل البيانات، تحديد اتجاهات الاستخدام، تحديد فعالية حملاتنا الترويجية ولتقييم وتحسين خدمتنا، المنتجات، الخدمات، التسويق وتجربتك."
          ],
          sharing: {
            content: "يجوز لنا مشاركة معلوماتك الشخصية في الحالات التالية:",
            items: [
              "<strong>مع مزودي الخدمة:</strong> يجوز لنا مشاركة معلوماتك الشخصية مع مزودي الخدمة لمراقبة وتحليل استخدام خدمتنا، للاتصال بك.",
              "<strong>لنقل الأعمال:</strong> يجوز لنا مشاركة أو نقل معلوماتك الشخصية فيما يتعلق بأو أثناء المفاوضات بشأن أي دمج، بيع أصول الشركة، التمويل، أو الاستحواذ على كل أو جزء من أعمالنا إلى شركة أخرى.",
              "<strong>مع الشركات التابعة:</strong> يجوز لنا مشاركة معلوماتك مع الشركات التابعة لنا، وفي هذه الحالة سنطالب تلك الشركات التابعة باحترام سياسة الخصوصية هذه. تشمل الشركات التابعة الشركة الأم لنا وأي شركات فرعية أخرى، شركاء المشاريع المشتركة أو الشركات الأخرى التي نتحكم فيها أو التي تخضع لسيطرة مشتركة معنا.",
              "<strong>مع شركاء الأعمال:</strong> يجوز لنا مشاركة معلوماتك مع شركائنا في الأعمال لتقديم منتجات أو خدمات أو عروض ترويجية معينة لك.",
              "<strong>مع مستخدمين آخرين:</strong> عندما تشارك معلومات شخصية أو تتفاعل بطريقة أخرى في المناطق العامة مع مستخدمين آخرين، يمكن أن يشاهد جميع المستخدمين هذه المعلومات وقد يتم توزيعها علنًا خارجيًا. إذا تفاعلت مع مستخدمين آخرين أو سجلت من خلال خدمة وسائل التواصل الاجتماعي من طرف ثالث، فقد ترى جهات الاتصال الخاصة بك على خدمة وسائل التواصل الاجتماعي من طرف ثالث اسمك، ملفك الشخصي، صورك ووصف نشاطك. وبالمثل، سيتمكن المستخدمون الآخرون من عرض أوصاف نشاطك، التواصل معك وعرض ملفك الشخصي.",
              "<strong>بموافقتك</strong>: يجوز لنا الكشف عن معلوماتك الشخصية لأي غرض آخر بموافقتك."
            ]
          }
        },
        retention: {
          title: "الاحتفاظ ببياناتك الشخصية",
          content: [
            "ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضروريًا للأغراض المنصوص عليها في سياسة الخصوصية هذه. سنحتفظ ببياناتك الشخصية ونستخدمها بالقدر اللازم للامتثال لالتزاماتنا القانونية (على سبيل المثال، إذا كنا مطالبين بالاحتفاظ ببياناتك للامتثال للقوانين المعمول بها)، وحل النزاعات، وتطبيق اتفاقياتنا وسياساتنا القانونية.",
            "ستحتفظ الشركة أيضًا ببيانات الاستخدام لأغراض التحليل الداخلي. يتم الاحتفاظ ببيانات الاستخدام بشكل عام لفترة زمنية أقصر، إلا عندما تُستخدم هذه البيانات لتعزيز الأمان أو لتحسين وظائف خدمتنا، أو إذا كنا ملزمين قانونًا بالاحتفاظ بهذه البيانات لفترات زمنية أطول."
          ]
        },
        transfer: {
          title: "نقل بياناتك الشخصية",
          content: [
            "تتم معالجة معلوماتك، بما في ذلك البيانات الشخصية، في مكاتب تشغيل الشركة وفي أي أماكن أخرى يتواجد فيها الأطراف المشاركون في المعالجة. هذا يعني أن هذه المعلومات يمكن نقلها إلى — والاحتفاظ بها على — أجهزة كمبيوتر موجودة خارج ولايتك، محافظتك، بلدك أو أي ولاية قضائية حكومية أخرى حيث قد تختلف قوانين حماية البيانات عن تلك الموجودة في ولايتك القضائية.",
            "موافقتك على سياسة الخصوصية هذه متبوعة بتقديمك لهذه المعلومات تمثل موافقتك على هذا النقل.",
            "ستتخذ الشركة جميع الخطوات اللازمة بشكل معقول لضمان معالجة بياناتك بأمان ووفقًا لسياسة الخصوصية هذه ولن يتم نقل بياناتك الشخصية إلى منظمة أو بلد ما لم تكن هناك ضوابط كافية مطبقة بما في ذلك أمان بياناتك ومعلوماتك الشخصية الأخرى."
          ]
        },
        deletion: {
          title: "حذف بياناتك الشخصية",
          content: [
            "لديك الحق في حذف أو طلب مساعدتنا في حذف البيانات الشخصية التي جمعناها عنك.",
            "قد تتيح لك خدمتنا حذف معلومات معينة عنك من داخل الخدمة.",
            "يمكنك تحديث، تعديل، أو حذف معلوماتك في أي وقت عن طريق تسجيل الدخول إلى حسابك، إذا كان لديك واحد، وزيارة قسم إعدادات الحساب الذي يتيح لك إدارة معلوماتك الشخصية. يمكنك أيضًا التواصل معنا لطلب الوصول إلى، تصحيح، أو حذف أي معلومات شخصية قدمتها لنا.",
            "يرجى ملاحظة، مع ذلك، أننا قد نحتاج إلى الاحتفاظ بمعلومات معينة عندما يكون لدينا التزام قانوني أو أساس قانوني للقيام بذلك."
          ]
        },
        disclosure: {
          title: "الكشف عن بياناتك الشخصية",
          business: {
            title: "المعاملات التجارية",
            content: "إذا كانت الشركة متورطة في دمج، استحواذ أو بيع أصول، فقد يتم نقل بياناتك الشخصية. سنقدم إشعارًا قبل نقل بياناتك الشخصية وتصبح خاضعة لسياسة خصوصية مختلفة."
          },
          law: {
            title: "إنفاذ القانون",
            content: "في ظل ظروف معينة، قد يُطلب من الشركة الكشف عن بياناتك الشخصية إذا كان ذلك مطلوبًا بموجب القانون أو استجابة لطلبات صالحة من السلطات العامة (مثل المحكمة أو وكالة حكومية)."
          },
          legal: {
            title: "المتطلبات القانونية الأخرى",
            content: "يجوز للشركة الكشف عن بياناتك الشخصية بحسن نية باعتقاد أن هذا الإجراء ضروري لـ:",
            items: [
              "الامتثال لالتزام قانوني",
              "حماية والدفاع عن حقوق أو ممتلكات الشركة",
              "منع أو التحقيق في أي مخالفات محتملة تتعلق بالخدمة",
              "حماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور",
              "الحماية من المسؤولية القانونية"
            ]
          }
        },
        security: {
          title: "أمان بياناتك الشخصية",
          content: "أمان بياناتك الشخصية مهم بالنسبة لنا، لكن تذكر أنه لا توجد طريقة نقل عبر الإنترنت، أو طريقة تخزين إلكترونية آمنة بنسبة 100%. بينما نسعى لاستخدام وسائل مقبولة تجاريًا لحماية بياناتك الشخصية، لا يمكننا ضمان أمانها المطلق."
        },
        children: {
          title: "خصوصية الأطفال",
          content: [
            "لا تخاطب خدمتنا أي شخص دون سن 13 عامًا. نحن لا نجمع عن علم معلومات تعريف شخصية من أي شخص دون سن 13 عامًا. إذا كنت والدًا أو وصيًا وكنت على علم بأن طفلك قد قدم لنا بيانات شخصية، يرجى التواصل معنا. إذا علمنا أننا جمعنا بيانات شخصية من أي شخص دون سن 13 عامًا دون التحقق من موافقة الوالدين، فإننا نتخذ خطوات لإزالة تلك المعلومات من خوادمنا.",
            "إذا كنا بحاجة إلى الاعتماد على الموافقة كأساس قانوني لمعالجة معلوماتك وكانت بلدك تتطلب موافقة من والد، فقد نطلب موافقة والدك قبل أن نجمع ونستخدم تلك المعلومات."
          ]
        },
        links: {
          title: "روابط إلى مواقع ويب أخرى",
          content: [
            "قد تحتوي خدمتنا على روابط لمواقع ويب أخرى لا نديرها. إذا نقرت على رابط طرف ثالث، ستتم إحالتك إلى موقع ذلك الطرف الثالث. ننصحك بشدة بمراجعة سياسة الخصوصية لكل موقع تزوره.",
            "ليس لدينا سيطرة ولا نتحمل المسؤولية عن المحتوى، سياسات الخصوصية أو الممارسات الخاصة بأي مواقع أو خدمات طرف ثالث."
          ]
        },
        changes: {
          title: "التغييرات على سياسة الخصوصية هذه",
          content: [
            "قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنخطرك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة.",
            "سنخبرك عبر البريد الإلكتروني و/أو إشعار بارز على خدمتنا، قبل أن تصبح التغييرات فعالة ونحدث تاريخ \"آخر تحديث\" في أعلى سياسة الخصوصية هذه.",
            "ينصح بمراجعة سياسة الخصوصية هذه بشكل دوري لأي تغييرات. التغييرات على سياسة الخصوصية هذه فعالة عندما يتم نشرها على هذه الصفحة."
          ]
        },
        contact: {
          title: "اتصل بنا",
          content: "إذا كانت لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك التواصل معنا:",
          items: [
            "عن طريق البريد الإلكتروني: info@legionagency.tech"
          ]
        }
      },
      footer: "تم إنشاؤه باستخدام <a href=\"https://www.termsfeed.com/privacy-policy-generator/\" style=\"color: var(--primary-color); text-decoration: none;\" target=\"_blank\">مولد سياسة الخصوصية TermsFeed</a>"
    }
  };


function PrivacyPolicy() {
  // Assuming useTheme and useLanguage provide valid context values
  const { darkMode } = useTheme() || {}; // Add default value or proper error handling
  const { language } = useLanguage() || { language: 'en' }; // Default to 'en' if context is missing
  const { isMobile } = useScreenSize(); // isTablet is defined but not used in this component
  const t = translations[language] || translations['en']; // Fallback to English if language not found
  const { ref, inView } = useInView({ triggerOnce: true, threshold: isMobile ? 0.1 : 0.3 });

  // Ensure CSS variables are defined globally in your CSS setup
  // e.g., :root { --tertiary-color: #f0f0f0; --text-default-color: #333; ... }
  // or using Tailwind's theme configuration

  return (
    <section
      id="privacy-policy"
      className="py-20 md:py-30" // Adjusted padding for responsiveness
      style={{
        backgroundColor: 'var(--tertiary-color)',
        color: 'var(--text-default-color)',
        transition: 'var(--transition-default)',
      }}
      dir={language === 'ar' ? 'rtl' : 'ltr'}
    >
      <div className={`container mx-auto px-4 sm:px-6 lg:px-8`}>
        {/* Title Section */}
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 50 }}
          animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 50 }}
          transition={{ duration: 0.8 }}
          className="mb-12 text-center" // Centered title
        >
          <p
            className="text-xs uppercase font-extrabold tracking-widest relative inline-block mb-2"
            style={{ color: 'var(--text-muted-color)' }}
          >
            {t.title}
            {/* Adjusted line position for better centering and responsiveness */}
            <span
              className={`absolute top-1/2 transform -translate-y-1/2 h-[2px] w-16 ${language === 'ar' ? 'right-full mr-4' : 'left-full ml-4'}`}
              style={{ backgroundColor: 'var(--primary-color)' }}
            ></span>
             <span
              className={`absolute top-1/2 transform -translate-y-1/2 h-[2px] w-16 ${language === 'ar' ? 'left-full ml-4' : 'right-full mr-4'}`}
              style={{ backgroundColor: 'var(--primary-color)' }}
            ></span>
          </p>
          <h2
            className={`text-3xl sm:text-4xl md:text-5xl font-extrabold font-raleway`}
            style={{ color: 'var(--text-heading-color)' }}
          >
            {t.subtitle}
          </h2>
        </motion.div>

        {/* Content Box */}
        <motion.div
          initial={{ opacity: 0 }} // Changed initial state for content box
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.3 }} // Slight delay after title
          className="p-6 md:p-10 lg:p-12" // Responsive padding
          style={{
            // Using CSS variables for border color as well
            border: '10px solid var(--bg-white-color)', // Thinner border
            backgroundColor: 'var(--card-bg)',
            borderRadius: '8px', // Added subtle rounding
            boxShadow: 'var(--shadow-medium)' // Added subtle shadow if defined
          }}
        >
          <div className="space-y-8"> {/* Increased spacing between sections */}
            <p className="text-sm" style={{ color: 'var(--text-muted-color)' }}>
              {t.lastUpdated}
            </p>
            {t.intro.map((para, index) => (
              <p key={`intro-${index}`} className="text-base leading-relaxed" style={{ color: 'var(--text-default-color)' }}>
                {para}
              </p>
            ))}

            {/* --- Sections Start --- */}

            {/* Interpretation and Definitions */}
            <Section
              id="interpretation-definitions"
              title={t.sections.interpretation.title}
              subsections={[
                {
                  title: t.sections.interpretation.interpretation.title,
                  content: t.sections.interpretation.interpretation.content
                },
                {
                  title: t.sections.interpretation.definitions.title,
                  content: t.sections.interpretation.definitions.content,
                  items: t.sections.interpretation.definitions.items
                }
              ]}
            />

            {/* Collecting and Using Your Personal Data */}
            <Section
              id="data-collection"
              title={t.sections.dataCollection.title}
              // Nested subsections for Types of Data
              subsections={[
                {
                  title: t.sections.dataCollection.types.title,
                  subsections: [ // This level contains the actual types
                    {
                      title: t.sections.dataCollection.types.personalData.title,
                      content: t.sections.dataCollection.types.personalData.content,
                      items: t.sections.dataCollection.types.personalData.items
                    },
                    {
                      title: t.sections.dataCollection.types.usageData.title,
                      content: t.sections.dataCollection.types.usageData.content // This is an array
                    },
                    {
                      title: t.sections.dataCollection.types.socialMedia.title,
                      content: t.sections.dataCollection.types.socialMedia.content, // This is an array
                      items: t.sections.dataCollection.types.socialMedia.items
                    },
                    {
                      title: t.sections.dataCollection.types.tracking.title,
                      content: t.sections.dataCollection.types.tracking.content, // This is an array
                      items: t.sections.dataCollection.types.tracking.items,
                      // Further nested subsections for Cookie Types
                      subsections: t.sections.dataCollection.types.tracking.cookieTypes.map(cookie => ({
                        title: cookie.title,
                        // Combine details into a single content string or handle differently in Section component
                        content: cookie.details.map((detail, i) => <p key={i} className="text-sm" style={{ color: 'var(--text-muted-color)'}}>{detail}</p>)
                      }))
                    }
                  ]
                }
              ]}
            />

            {/* Use of Your Personal Data */}
            <Section
              id="use-of-data"
              title={t.sections.use.title}
              content={t.sections.use.content}
              items={t.sections.use.items}
              subsections={[ // Subsection for Sharing information
                {
                  // No title needed here based on structure, just content and items
                  content: t.sections.use.sharing.content,
                  items: t.sections.use.sharing.items
                }
              ]}
            />

            {/* Retention of Your Personal Data */}
            <Section
              id="retention"
              title={t.sections.retention.title}
              content={t.sections.retention.content} // This is an array
            />

            {/* Transfer of Your Personal Data */}
            <Section
              id="transfer"
              title={t.sections.transfer.title}
              content={t.sections.transfer.content} // This is an array
            />

            {/* Delete Your Personal Data */}
            <Section
              id="deletion"
              title={t.sections.deletion.title}
              content={t.sections.deletion.content} // This is an array
            />

            {/* Disclosure of Your Personal Data */}
            <Section
              id="disclosure"
              title={t.sections.disclosure.title}
              subsections={[
                {
                  title: t.sections.disclosure.business.title,
                  content: t.sections.disclosure.business.content
                },
                {
                  title: t.sections.disclosure.law.title,
                  content: t.sections.disclosure.law.content
                },
                {
                  title: t.sections.disclosure.legal.title,
                  content: t.sections.disclosure.legal.content,
                  items: t.sections.disclosure.legal.items
                }
              ]}
            />

            {/* Security of Your Personal Data */}
            <Section
              id="security"
              title={t.sections.security.title}
              content={t.sections.security.content}
            />

            {/* Children's Privacy */}
            <Section
              id="childrens-privacy"
              title={t.sections.children.title}
              content={t.sections.children.content} // This is an array
            />

            {/* Links to Other Websites */}
            <Section
              id="links"
              title={t.sections.links.title}
              content={t.sections.links.content} // This is an array
            />

            {/* Changes to this Privacy Policy */}
            <Section
              id="changes"
              title={t.sections.changes.title}
              content={t.sections.changes.content} // This is an array
            />

            {/* Contact Us */}
            <Section
              id="contact"
              title={t.sections.contact.title}
              content={t.sections.contact.content}
              items={t.sections.contact.items} // Correctly passed items prop
            />

            {/* --- Sections End --- */}

          </div>
        </motion.div>

    
       
      </div>
    </section>
  );
}

// Section Component (Refined)
const Section = ({ id, title, content, items, subsections }) => {
    const { isMobile } = useScreenSize();
    const { ref, inView } = useInView({ triggerOnce: true, threshold: isMobile ? 0.1 : 0.2 });
    const { language } = useLanguage() || { language: 'en' };
  
    return (
      <motion.div
        ref={ref}
        id={id}
        initial={{ opacity: 0, y: 30 }}
        animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
        transition={{ duration: 0.6, ease: 'easeOut' }}
        className="space-y-4 pt-4"
      >
        {/* Section Title */}
        {title && (
          <h3
            className="text-xl sm:text-2xl font-bold font-raleway border-b pb-2"
            style={{ color: 'var(--text-heading-color)', borderColor: 'var(--primary-color-light)' }}
          >
            {title}
          </h3>
        )}
  
        {/* Section Content (Handles string or array) */}
        {content &&
          (Array.isArray(content) ? (
            content.map((para, index) => (
              <p
                key={`content-${index}`}
                className="text-base leading-relaxed"
                style={{ color: 'var(--text-default-color)' }}
              >
                {typeof para === 'string' ? para : para}
              </p>
            ))
          ) : typeof content === 'string' ? (
            <p className="text-base leading-relaxed" style={{ color: 'var(--text-default-color)' }}>
              {content}
            </p>
          ) : (
            content
          ))}
  
        {/* Section Items (List) */}
        {items && (
          <ul className={`space-y-2 list-disc ${language === 'ar' ? 'pr-5' : 'pl-5'}`}>
            {items.map((item, index) => (
              typeof item === 'string' && (item.includes('<') || item.includes('&')) ? (
                <li
                  key={`item-${index}`}
                  className="text-base leading-relaxed"
                  style={{ color: 'var(--text-default-color)' }}
                  dangerouslySetInnerHTML={{ __html: item }}
                />
              ) : (
                <li
                  key={`item-${index}`}
                  className="text-base leading-relaxed"
                  style={{ color: 'var(--text-default-color)' }}
                >
                  {item}
                </li>
              )
            ))}
          </ul>
        )}
  
        {/* Render Subsections Recursively */}
        {subsections &&
          subsections.map((subsection, index) => (
            <div
              key={`sub-${index}`}
              className={`${language === 'ar' ? 'mr-4 pr-4 border-r' : 'ml-4 pl-4 border-l'} border-gray-300 space-y-3`}
            >
              {/* Subsection Title (h4) */}
              {subsection.title && (
                <h4
                  className="text-lg sm:text-xl font-semibold font-raleway mt-4"
                  style={{ color: 'var(--text-heading-color)' }}
                >
                  {subsection.title}
                </h4>
              )}
  
              {/* Subsection Content */}
              {subsection.content &&
                (Array.isArray(subsection.content) ? (
                  subsection.content.map((para, i) => (
                    <div
                      key={`sub-content-${i}`}
                      className="text-base leading-relaxed"
                      style={{ color: 'var(--text-default-color)' }}
                    >
                      {typeof para === 'string' ? para : para}
                    </div>
                  ))
                ) : typeof subsection.content === 'string' ? (
                  <p className="text-base leading-relaxed" style={{ color: 'var(--text-default-color)' }}>
                    {subsection.content}
                  </p>
                ) : (
                  subsection.content
                ))}
  
              {/* Subsection Items */}
              {subsection.items && (
                <ul className={`space-y-1 list-disc ${language === 'ar' ? 'pr-5' : 'pl-5'} mt-2`}>
                  {subsection.items.map((item, i) => (
                    typeof item === 'string' && (item.includes('<') || item.includes('&')) ? (
                      <li
                        key={`sub-item-${i}`}
                        className="text-base"
                        style={{ color: 'var(--text-default-color)' }}
                        dangerouslySetInnerHTML={{ __html: item }}
                      />
                    ) : (
                      <li
                        key={`sub-item-${i}`}
                        className="text-base"
                        style={{ color: 'var(--text-default-color)' }}
                      >
                        {item}
                      </li>
                    )
                  ))}
                </ul>
              )}
  
              {/* Nested Subsections (e.g., Cookie Types) */}
              {subsection.subsections &&
                subsection.subsections.map((sub, i) => (
                  <div
                    key={`sub-sub-${i}`}
                    className={`${language === 'ar' ? 'mr-4 pr-4 border-r' : 'ml-4 pl-4 border-l'} border-gray-200 space-y-2 mt-3`}
                  >
                    {/* Nested Subsection Title (h5) */}
                    {sub.title && (
                      <h5
                        className="text-md sm:text-lg font-semibold font-raleway"
                        style={{ color: 'var(--text-heading-color)' }}
                      >
                        {sub.title}
                      </h5>
                    )}
                    {/* Nested Subsection Content */}
                    {sub.content &&
                      (Array.isArray(sub.content) ? (
                        sub.content.map((para, j) => (
                          <div
                            key={`sub-sub-content-${j}`}
                            className="text-base"
                            style={{ color: 'var(--text-default-color)' }}
                          >
                            {typeof para === 'string' ? para : para}
                          </div>
                        ))
                      ) : typeof sub.content === 'string' ? (
                        <p className="text-base" style={{ color: 'var(--text-default-color)' }}>
                          {sub.content}
                        </p>
                      ) : (
                        sub.content
                      ))}
                  </div>
                ))}
            </div>
          ))}
      </motion.div>
    );
  };

export default PrivacyPolicy;